CREATE TABLE IF NOT EXISTS site_feedback (
ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
USER_NAME VARCHAR(255) NOT NULL,
MESSAGE TEXT NOT NULL,
RATING TINYINT UNSIGNED NOT NULL,
ACTIVE char(1) NOT NULL DEFAULT 'Y',
DATE_CREATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (ID),
INDEX idx_active (ACTIVE),
INDEX idx_rating (RATING),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

