CREATE TABLE IF NOT EXISTS site_feedback (
ID int(11) NOT NULL AUTO_INCREMENT,
USER_NAME varchar(255) NOT NULL,
MESSAGE text NOT NULL,
RATING int(2) NOT NULL,
ACTIVE char(1) DEFAULT 'Y',
DATE_CREATE datetime DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (ID)
);